logging:
  level:
    org:
      springframework:
        security: INFO
server:
  port: 8081
stratinit:
  email:
    hostname: localhost
    enabled: false
  scheduler:
    enabled: true
  mode: TEST
  jwt:
    secret: dGhpcyBpcyBhIDI1NiBiaXQgc2VjcmV0IGtleSBmb3Igand0IHNpZ25pbmc=
    expiration-ms: 86400000
  cors:
    allowed-origins: http://localhost:5173
