spring:
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
logging:
  level:
    org:
      springframework:
        security: INFO
server:
  port: 8081
stratinit:
  version: 1.2.8
  email:
    hostname: localhost
    enabled: false
    from-address: hq@strategicinitiative.org
    admin-address: ken.stevens@sympatico.ca
  scheduler:
    enabled: true
  mode: TEST
  jwt:
    secret: dGhpcyBpcyBhIDI1NiBiaXQgc2VjcmV0IGtleSBmb3Igand0IHNpZ25pbmc=
    expiration-ms: 86400000
  cors:
    allowed-origins: http://localhost:5173
